### ISSUE TITLE
Export Type for Responsive Grid

### ISSUE THREAD

**Issue by lucferrario** [iNerdStack/react-native-flexible-grid#3]
Hey! I am right now in need of a type to extend my custom interface for my grid component.

That's what i mean:
```
interface GridProps extends Omit<FlatListProps<any>, "renderItem" | "data"> {
  data: {
    id: string;
    src: string;
    type?: string;
  }[];
  ListHeaderComponent?:
    | React.ReactElement<any>
    | React.ComponentType<any>
    | null;
}
```

I'd like to have a custom type with the props needed for the ResponsiveGrid, since for the FlexGrid they're pretty much the same as a FlatList. It's not the case with the ResponsiveGrid though, and I'd almost need to pass them all manually.

**Comment by iNerdStack** [comment]
Hello @lucaferrarioo 
A new version [(0.1.9)](https://www.npmjs.com/package/react-native-flexible-grid/v/0.1.9) has been published now with <code>ResponsiveGridProps</code> and <code>FlexGridProps</code> types exported. you can access the types by importing them

```jsx
import { FlexGridProps, ResponsiveGridProps } from 'react-native-flexible-grid';

```

**Comment by lucferrario** [comment]
Thanks a lot, appreciate it!
